import { StoreProvider } from '@/stores/StoreProvider'
import './styles/globals.css'
import { InitialState } from '@/stores/RootStore/RootStore'
import Header from '@/components/Layout/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const initialState: InitialState = {
  userStore: {},
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen w-screen overflow-x-hidden">
        <StoreProvider initialState={initialState}>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
